[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = '''
#     source ~/.config/dein/plugins/deoplete.vim
# '''
# on_i = 1

[[plugins]]
    repo = 'Shougo/neco-vim'
    on_source = ['deoplete']

[[plugins]]
    repo = 'Shougo/neco-syntax'
    on_source = ['deoplete']

# [[plugins]]
# repo = 'deoplete-plugins/deoplete-jedi'
# on_source = ['deoplete']
# on_ft = 'python'
# hook_add = '''
#     let g:deoplete#sources#jedi#python_path = substitute(substitute(system("which python")[:-2],"/c","c:","g"),"/",'\',"g")
# '''
# #     let g:deoplete#sources#jedi#python_path = 'c:\ProgramData\Anaconda3\envs\test_py27\python'

[[plugins]]
    repo = 'JuliaEditorSupport/deoplete-julia'
    on_source = ['deoplete']

[[plugins]]
    repo = 'deoplete-plugins/deoplete-zsh'
    on_source = ['deoplete']

# [[plugins]]
#     repo = 'lighttiger2505/deoplete-vim-lsp'
#     on_source = ['deoplete']


