[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
    source ~/.config/dein/plugins/deol.vim
'''

# [[plugins]]
# repo = 'Shougo/vimshell.vim'
# hook_add = '''
#     source ~/.config/dein/plugins/vimshell.vim
# '''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
    source ~/.config/dein/plugins/defx.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    source ~/.config/dein/plugins/quickrun.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/.config/dein/plugins/denite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'joshdick/onedark.vim'

# [[plugins]]
# repo = 'mattn/vim-lsp-settings'
#
# [[plugins]]
# repo = 'prabirshrestha/async.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'

# [[plugins]]
# repo = 'ryanolsonx/vim-lsp-python'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
    source ~/.config/dein/plugins/coc.vim
'''
[[plugins]]
repo = 'neoclide/coc-snippets'

[[plugins]]
repo = 'neoclide/coc-neco'

[[plugins]]
repo = 'Shougo/neco-vim'

